<center><h1><u>Recherche Opérationnelle</u></h1></center>

## <u>1- Contexte</u>

Nous sommes des contrebandiers intergalactiques, nous devons livrer notre spotchka dans toute la galaxie. Pour cela nous faisons partir plusieurs vaisseau en parallèle, l'objectif minimiser la distance du vaisseau qui fait la plus grande distance.
Cependant, la Spotchka étant illégale nous devons éviter les douanes.

## <u>2- Définitions mathématiques</u>
Avant de se lancer dans l'implémentation d'algorithme nous allons commencé par formaliser le probléme de maniére mathématiques. Cela vas par la suite nous permettre de définir précisement les variables et les contraintes et d'etablir la fonction objectif de nos algorithmes.

<div style="margin-left: 40px;">

### 2.1 Caractéristiques

</div>

L'ensemble des planètes est représenté par :
$$ V = [0;n] $$

La planète 0 étant notre planète de départ.

Sachant que nous sommes dans l'espace nous pouvons rejoindre toutes les planète depuis n'importe quelle autre planète.

On peut donc noter : $$ G = (V, E) $$ où $$ E = {(i,j) / i \neq j, i \in V, j \in V} $$

Chaque arête va posséder :
- Une distance : $ d_{ij} > 0 $
- Un risque : $ r_{ij} > 0 $

Un certain nombre de vaisseaux sont disponibles, on note : $ K \geq 1 $

Sachant que chaque vaisseau doit partir de la planète 0 et y revenir après sa tournée.

<div style="margin-left: 40px;">

### 2.2 Variables

</div>

Variable de décision :

$$ x_{ij}^k = \{0, 1\}$$
Avec 1 si le vaisseau $k$ emprunte l'arête $ij$, 0 sinon.

<div style="margin-left: 40px;">

###  2.3 Fonction objectif

</div>

Notre objectif est de minimiser la distance du vaisseau qui a parcouru la distance maximale.

On peut donc définir la fonction abjectif suivante :
$$ \min(\max_k(\sum_{i=0}^{n} \sum_{j=0}^{n} x_{ij}^k * d_{ij}))

<div style="margin-left: 40px;">

### 2.4 Contraintes

</div>

- Livraison complète : chaque planète doit être visitée une seule fois. Soit 1 seul vaisseau rentre dans la planète et en ressort.
    + Entrée unique :
    $$ \sum_{k=1}^{K} \sum_{j=0}^{n} x_{ij}^k = 1 \quad \forall \: i \neq 0 $$

    + Sortie unique :
    $$ \sum_{k=1}^{K} \sum_{i=0}^{n} x_{ij}^k = 1 \quad \forall \: j \neq 0 $$
    

- Tournées valides : Chaque vaisseau doit partir de la planète 0 et y revenir à la fin.
    + Départ dépôt :
    $$ \sum_{j=0}^{n} x_{0j}^k = 1  \quad \forall \: k $$

    + Retour dépôt :
    $$ \sum_{i=0}^{n} x_{i0}^k = 1  \quad \forall \: k $$
- Risque : chaque vaisseau possède un nombre limité de vies $ R_{max}^k $ 
Pour chaque vaisseau $k$ le risque total des arètes doit être inférieur à son risque max.
$$ \sum_{i=0}^{n} \sum_{j=0}^{n} x_{ij}^k * r_{ij} \leq R_{max}^k $$

## <u>3- Analyse de difficulté</u>
Nous allons désormais passer à l'analyse de la difficulté basée sur la complexité. Cette analyse est importante car elle nous permettra de justifier les choix de métaheuristiques que nous allons mettre en place sur le problème.

Pour démontrer que notre problème est **NP-difficile**, nous utilisons une **réduction polynomiale**. On va montrer que si nous possédions un algorithme capable de résoudre ton problème en un temps raisonnable, nous pourrions résoudre un problème dont nous savons déjà qu'il est **NP-difficile**.

Le candidat idéal pour cette démonstration est le **TSP classique** (Traveling Salesman Problem).

<div style="margin-left: 40px;">

### 3.1 La preuve par restriction

</div>

La manière la plus simple de prouver la complexité d'un problème est de montrer qu'un problème **NP-difficile** connu est un **cas particulier** de notre problème.

<div style="margin-left: 40px;">

### 3.2 Rappel du problème TSP (Problème $P'$)

</div>

Le TSP classique consiste à trouver une tournée unique ($k=1$) visitant tous les sommets une seule fois et minimisant la distance totale. Nous savons que le **TSP** est **NP-difficile**.

<div style="margin-left: 40px;">

### 3.3 Construction de l'instance (La Réduction)

</div>

Supposons que nous avons une instance quelconque du **TSP** : un graphe $G = (V, E)$ avec des poids $c_{ij}$ sur les arêtes. Pour transformer cela en une instance de notre problème, nous fixons les paramètres de la manière suivante :

* **Nombre de véhicules :** On pose $k = 1$.
* **Contrainte de vie :** On pose $v_{ij} = 0$ pour toutes les arêtes du graphe (les arêtes ne font perdre aucune vie).
* **Objectif :** Minimiser la longueur de la tournée la plus longue.


<div style="margin-left: 40px;">

### 3.4 Analyse

</div>

Dans cette configuration spécifique :
1.  Puisqu'il n'y a qu'un seul véhicule ($k=1$),et que chaque sommet doit être visité exactement une fois : La solution recherchée est obligatoirement un **cycle hamiltonien**. Minimiser $Z$ revient alors à trouver, parmi tous les cycles hamiltoniens possibles, celui qui a la somme des poids la plus faible. C'est la définition exacte du **TSP**...

2.  Puisque le coût en vies $v_{ij}$ est nul partout, notre contrainte des "3 vies" est toujours satisfaite (on perd 0 vie, ce qui est inférieur à 3). Elle n'influence donc pas la recherche de la solution.

L'instance du problème se comporte alors exactement comme une instance du **TSP classique**. 

<div style="margin-left: 40px;">

### 3.5 Conclusion de la réduction

</div>

Si nous avions un algorithme polynomial pour résoudre notre problème, nous pourrions résoudre n'importe quel **TSP** en temps polynomial en utilisant la transformation ci-dessus. 

Comme le **TSP** est **NP-difficile**, notre problème est **au moins aussi difficile** que lui. On dit alors qu'il est **NP-difficile**.

<div style="margin-left: 40px;">

### 3.6 Résumé

</div
>
Notre problème combine trois sources de complexité distinctes :

* **La composante Partitionnement (NP-difficile) :** Même sans notion de distance, répartir $n$ sommets entre $k$ véhicules pour équilibrer la charge (le Min-Max) est une variante du *Multiprocessor Scheduling* ou du *Bin Packing*.
* **La composante Hamiltonienne (NP-difficile) :** Trouver l'ordre de passage optimal dans chaque groupe de sommets reste un TSP.
* **La composante Sac à Dos (NP-difficile) :** La contrainte de ressources (les 3 vies) ajoute une dimension de type *Knapsack*. Sur chaque chemin, nous devons vérifier que nous ne dépassons pas une capacité (ici, 2 vies perdues max).

In [11]:
import numpy as np
import random
import math
import copy
import matplotlib.pyplot as plt
import pulp

def generer_matrices(t, difficulte=0.5, seed=1):
    """
    Génère deux matrices complètes :
    - MATRICES_P : distances positives symétriques
    - MATRICES_R : dangerosité (0 à 5), symétrique, influencée par 'difficulte'
    
    Paramètres :
    - t : taille de la matrice
    - difficulte : float entre 0 et 1 (0 = facile, 1 = très dangereux)
    - seed : pour reproductibilité
    
    Retour :
    - MATRICES_P (np.array)
    - MATRICES_R (np.array)
    """
    
    dist_min=10
    dist_max=80

    
    np.random.seed(seed)
    random.seed(seed)

    # -------------------------
    # MATRICE DES DISTANCES
    # -------------------------
    dist_matrix = np.random.randint(dist_min, dist_max + 1, size=(t, t))
    np.fill_diagonal(dist_matrix, 0)
    dist_matrix = (dist_matrix + dist_matrix.T) // 2  # symétrie

    # -------------------------
    # MATRICE DES COÛTS EN VIES
    # -------------------------
    MATRICES_R = np.zeros((t, t), dtype=int)

    for i in range(t):
        for j in range(i + 1, t):

            # probabilité d'avoir un coût élevé
            if random.random() < difficulte:
                # coût dangereux : 3 à 5
                cost = np.random.randint(3, 6)
            else:
                # coût faible : 0 à 2
                cost = np.random.randint(0, 3)

            MATRICES_R[i, j] = cost
            MATRICES_R[j, i] = cost

    return dist_matrix, MATRICES_R

P1 = generer_matrices(10)[0]
R1 = generer_matrices(10)[1]

P2 = generer_matrices(20)[0]
R2 = generer_matrices(20)[1]

P3 = generer_matrices(50)[0]
R3 = generer_matrices(50)[1]

MATRICES_P = [P1, P2, P3]
MATRICES_R = [R1, R2, R3]

# Affichage des matrices
for i in range(len(MATRICES_P)):
    print(f"Matrice P{i+1} (Distances) :\n{MATRICES_P[i]}\n")
    print(f"Matrice R{i+1} (Coûts en vies) :\n{MATRICES_R[i]}\n")


Matrice P1 (Distances) :
[[ 0 26 18 36 63 30 26 40 44 46]
 [26  0 47 39 37 28 52 76 26 18]
 [18 47  0 22 64 15 15 41 29 28]
 [36 39 22  0 41 68 50 11 62 32]
 [63 37 64 41  0 53 51 25 17 39]
 [30 28 15 68 53  0 41 64 51 20]
 [26 52 15 50 51 41  0 68 60 54]
 [40 76 41 11 25 64 68  0 49 43]
 [44 26 29 62 17 51 60 49  0 27]
 [46 18 28 32 39 20 54 43 27  0]]

Matrice R1 (Coûts en vies) :
[[0 3 0 2 5 5 3 1 2 5]
 [3 0 5 2 3 2 4 4 2 3]
 [0 5 0 2 0 5 4 1 1 5]
 [2 2 2 0 4 4 3 5 3 4]
 [5 3 0 4 0 3 4 4 3 4]
 [5 2 5 4 3 0 4 1 2 1]
 [3 4 4 3 4 4 0 3 0 2]
 [1 4 1 5 4 1 3 0 4 3]
 [2 2 1 3 3 2 0 4 0 0]
 [5 3 5 4 4 1 2 3 0 0]]

Matrice P2 (Distances) :
[[ 0 19 36 28 63 23 23 21 26 44 39 42 34 48 42 25 38 46 24 31]
 [19  0 53 38 48 37 17 54 30 50 54 26 46 75 43 53 46 32 50 43]
 [36 53  0 35 32 77 50 45 17 35 57 49 31 78 35 29 43 64 38 33]
 [28 38 35  0 35 55 62 66 51 40 50 65 33 16 27 47 50 39 35 37]
 [63 48 32 35  0 56 47 71 37 38 45 40 35 38 27 19 73 68 51 13]
 [23 37 77 55 56  0 45 35 50 33 45 41 49 2

# Métaheurestiques :

## ACO

## <u>4 - Implémentation d'algorithme  </u>
Maintenant que nous avons démontré que notre probléme est np-difficile, nous savons  qu'il n'existe probablement pas d'algorithme exact capable de résoudre toutes les instances en temps polynomial.
Elle ne vont pas fonctionner car :
- Les algorithmes exacts (comme la programmation dynamique) ont une complexité exponentielle en fonction du nombre de planètes (n) et de vaisseaux (K). Par exemple :
    + Pour le TSP sous-jacent, la complexité est (O(n!)), ce qui devient impraticable dès (n > 20).
    + Notre problème combine TSP (ordonnancement des tournées), partitionnement (répartition des planètes entre vaisseaux) et sac à dos (contraintes de risque), amplifiant la difficulté.
   
Donc de cette analyse en découle l'utilisation des méta-heuristiques qui vont être les seules approches viable pour obtenir un résultant de qualité dans un temps raisonnables :
- Elles vont explorer l'espace de solutions de maniére heuristique.
- Elles ne garantissent pas l'optimalité globale, mais vont nous permettre de bon optimum local.
- Elle ne vont pas prendre 2 jours à s'executer.

<div style="margin-left: 40px;">

### 4.1 ACO (Optimisation par Colonies de Fourmis)

</div
> 

Nous allons essayer d'expliquer simplement le fonctionnement de l'algorithme.Il faut imaginé une colonie de fourmis qui cherche de la nourriture : au début, elles partent dans toutes les directions au hasard. Lorsqu’une fourmi trouve une miette de sucre, elle rentre au nid en déposant sur le sol une trace odorante, la phéromone. Si le chemin est court, la fourmi fait plus d'allers-retours, ce qui renforce l'odeur très rapidement. À l'inverse, sur un chemin long, l'odeur a le temps de s'évaporer. Les autres fourmis, attirées par la trace la plus forte, finissent par toutes choisir le chemin le plus efficace. En informatique, l'ACO vas donc copie ce comportement.

Donc notre cas ACO vas être trés intéressant car :
- structure TSP / multi-tournées : ACO construit des routes étape par étape, ce qui correspond à la recherche de tournées pour des vaisseaux.
- objectif min-max : on cherche à équilibrer plusieurs tournées, pas seulement une distance totale. ACO peut explorer plusieurs solutions en parallèle  et renforcer les arcs qui participent à de bonnes tournées.
- contraintes de risque : dans notre implémentation on filtre les arcs non faisables, donc les fourmis restent dans l’espace des solutions valides et apprennent sur des chemins compatibles avec le budget de vies.

In [13]:
def aco(MATRICES_P, MATRICES_R, K=3, MAX_LIFE=15, alpha=1, beta=2, rho=0.4, Q=50, num_ants=40, num_iterations=2000):
    """
    MATRICES_P : Matrice des distances (n x n)
    MATRICES_R : Matrice des coûts de vie (n x n)
    """
    n = MATRICES_P.shape[0]
    
    # Initialisation des phéromones et de l'heuristique
    pheromone = np.ones((n, n))
    # On évite la division par zéro
    heuristic = 1 / (MATRICES_P + 1e-10)
    np.fill_diagonal(heuristic, 0)

    # --- Fonctions internes ---
    def get_route_distance(route):
        return sum(MATRICES_P[route[i], route[i+1]] for i in range(len(route)-1))

    def evaluate_solution(routes, unvisited_left):
        distances = [get_route_distance(r) for r in routes]
        # Pénalité forte si des villes ne sont pas visitées
        if unvisited_left > 0:
            penalty = 10000 * unvisited_left
            return max(distances) + penalty, distances
        return max(distances), distances

    def choose_next(current, unvisited, life_left):
        # Filtrage par contrainte de vie
        feasible = [j for j in unvisited if MATRICES_R[current, j] <= life_left]
        if not feasible:
            return None

        weights = []
        total = 0
        for j in feasible:
            w = (pheromone[current, j] ** alpha) * (heuristic[current, j] ** beta)
            weights.append(w)
            total += w

        if total == 0:
            return random.choice(feasible)

        r = random.random() * total
        s = 0
        for j, w in zip(feasible, weights):
            s += w
            if s >= r:
                return j
        return feasible[-1]

    def build_solution():
        unvisited = set(range(1, n))
        routes = [[0] for _ in range(K)]
        life_left = [MAX_LIFE] * K
        vehicle = 0
        stuck_count = 0 

        while unvisited:
            current = routes[vehicle][-1]
            nxt = choose_next(current, list(unvisited), life_left[vehicle])

            if nxt is None:
                if routes[vehicle][-1] != 0:
                    routes[vehicle].append(0)
                
                vehicle = (vehicle + 1) % K
                stuck_count += 1
                if stuck_count >= K:
                    break
                continue

            stuck_count = 0
            routes[vehicle].append(nxt)
            life_left[vehicle] -= MATRICES_R[current, nxt]
            unvisited.remove(nxt)
            vehicle = (vehicle + 1) % K

        for v in range(K):
            if routes[v][-1] != 0:
                routes[v].append(0)

        return routes, len(unvisited)

    # --- Boucle ACO ---
    best_solution = None
    best_cost = float("inf")
    best_distances = []
    best_unvisited = n

    historique = []

    for it in range(num_iterations):
        solutions = []
        for _ in range(num_ants):
            routes, unvisited_left = build_solution()
            cost, distances = evaluate_solution(routes, unvisited_left)
            solutions.append((routes, cost, distances, unvisited_left))

            if cost < best_cost:
                best_cost = cost
                best_solution = routes
                best_distances = distances
                best_unvisited = unvisited_left

        # Évaporation
        pheromone *= (1 - rho)

        historique.append((best_cost))

        # Mise à jour des phéromones (Top 3 solutions valides)
        solutions.sort(key=lambda x: x[1])
        for routes, cost, distances, unvisited_left in solutions[:3]:
            if unvisited_left > 0:
                continue
            deposit = Q / (cost + 1e-10)
            for route in routes:
                for i in range(len(route)-1):
                    a, b = route[i], route[i+1]
                    pheromone[a, b] += deposit
                    pheromone[b, a] += deposit

    # --- Préparation du retour ---
    is_feasible = (best_unvisited == 0)
    
    # Transformation des routes en dictionnaire "1", "2", "3"...
    cycles_vaisseaux = {}
    if best_solution:
        for idx, r in enumerate(best_solution):
            cycles_vaisseaux[str(idx + 1)] = r
    else:
        # Cas où aucune solution n'a été construite du tout
        cycles_vaisseaux = {str(i+1): [0, 0] for i in range(K)}

    max_dist = max(best_distances) if best_distances else 0.0

    return is_feasible, cycles_vaisseaux, max_dist, historique

## VNS

### Solution initiale

Cette fonction construit une solution de départ en distribuant les planètes aux vaisseaux de manière gloutonne. À chaque étape on affecte la planète au vaisseau le moins chargé, en respectant les contraintes de risque.

*Le terme glouton signifie qu'à chaque étape on prend la meilleure décision locale (ici le vaisseau le moins chargé) sans jamais revenir en arrière. C'est rapide mais pas optimal, le VNS viendra améliorer cette solution de départ par la suite.*

### Voisinage

Dans notre problème nous avons des planètes à répartir entre K vaisseaux, ce qui génère un espace de solutions combinatoire très grand, énumérer tous les voisins à chaque itération est donc impraticable.\
<br>
Pour explorer efficacement cet espace on utilise une recherche par **voisinage stochastique** : au lieu d'examiner tous les voisins, on tire aléatoirement une direction dans trois structures de voisinage complémentaires (2-opt, relocate, swap). Le VNS change de structure quand il ne trouve plus d'amélioration, évitant ainsi de rester bloqué dans un optimum local.\
<br>
Le multi-start renforce cette diversification en relançant l'algorithme depuis plusieurs points de départ aléatoires et en conservant le meilleur résultat global.

### Objectif des trois algorithmes

- **voisin_2opt** va venir modifier la plus grosse tournée en générant un segment aléatoire pour éviter d'énumérer tous les voisins.

- **voisin_relocate** a pour objectif de venir soulager le vaisseau avec la plus grande tournée. Il choisit aléatoirement une planète parmi la tournée et l'attribut à un des autres vaisseaux à une place aléatoire. La fonction vient rééquilibrer la charge entre les vaisseaux.

- **voisin_swap_inter** échange une planète entre deux vaisseaux tirés aléatoirement, sans modifier la taille des tournées. Son rôle est la diversification en explorant des combinaisons différentes.

### VNS (Variable Neighborhood Search)

Le VNS est la colonne vertébrale du programme. Il orchestre les trois voisinages pour explorer l'espace de solutions et converger vers le meilleur résultat trouvé.\
<br>
Un algorithme de recherche locale classique utilise un seul voisinage et s'arrête dès qu'il ne trouve plus d'amélioration. Le problème : il est bloqué dans un optimum local sans pouvoir en sortir.\
<br>
Le VNS résout ça en utilisant plusieurs voisinage qui explore chacun une dimension différente de l'espace.

- 2-opt → modifie l'ordre dans une tournée
- relocate → modifie la répartition entre vaisseaux
- swap inter → modifie les combinaisons de planètes

Quand le 2-opt est bloqué, relocate peut débloquer une direction que le 2-opt ne voit pas — et inversement. Les voisinages se complètent au lieu de se répéter.\
<br>
Le coeur du VNS se trouve dans le principe de retour au voisinage 0. Dès qu'on trouve une amélioration, on revient au voisinage le plus efficace (2-opt) pour exploiter cette nouvelle région. On n'avance dans les voisinages que quand on est vraiment bloqué.\
<br>
Cependant il faut rester vigilant, le VNS reste une métaheuristique — il ne garantit pas de trouver l'optimum global, seulement une bonne solution en temps raisonnable.


In [17]:
def vns_search(MATRICES_P, MATRICES_R, K=3, MAX_LIFE=15, MAX_ITER=2000, MAX_VOISIN=3):
    """
    Exécute la recherche de voisinage variable (VNS).
    
    Retourne:
    - is_feasible (bool)
    - cycles_vaisseaux (dict)
    - max_distance (float)
    """
    
    # ============================================================
    # ---------------------- OUTILS INTERNES ---------------------
    # ============================================================
    
    def distance_tournee(route, matrice_p):
        return sum(matrice_p[route[i]][route[i+1]] for i in range(len(route)-1))

    def evaluer(routes, matrice_p, matrice_r):
        """Retourne la distance max (Min-Max)."""
        return max(distance_tournee(r, matrice_p) for r in routes)

    def route_lives(route, matrice_r):
        return sum(matrice_r[route[i]][route[i+1]] for i in range(len(route)-1))

    def est_valide(routes, matrice_p, matrice_r):
        """Vérifie les contraintes de vie et la visite de tous les nœuds."""
        N = len(matrice_p)
        visited = []
        for r in routes:
            if route_lives(r, matrice_r) > MAX_LIFE:
                return False
            visited.extend(r[1:-1])
        return sorted(visited) == list(range(1, N))

    def solution_initiale(planetes, matrice_p, matrice_r):
        """Répartition simple pour démarrer."""
        routes = [[0] for _ in range(K)]
        for i, p in enumerate(planetes):
            routes[i % K].append(p)
        for r in routes:
            r.append(0)
        return routes

    # ============================================================
    # ----------------------- VOISINAGES -------------------------
    # ============================================================

    def voisin_2opt(solution: list[list], matrice_p) -> list[list]:
        """
        2opt : choisit le vaisseau avec la tournée la plus longue et inverse un segment aléatoire de sa tournée.
        
        Avant :
            Tournée de départ (Vaisseau 1 le plus long) : [0, 1, 2, 3, 0]
            On tire i=1 et j=3 → segment [1, 2, 3]
            On inverse ce segment → [3, 2, 1]
        Après :
            Tournée modifiée : [0, 3, 2, 1, 0]
            2 arêtes supprimés : (0 → 1) et (2 → 3)
            2 arêtes ajoutés : (0 → 3) et (1 → 0)
        """
        sol = copy.deepcopy(solution)                                           # Deep copy pour éviter de modifier la solution originale
        k_max = max(range(K), key=lambda k: distance_tournee(sol[k], matrice_p))           # Trouve le vaisseau avec la tournée la plus longue
        t = sol[k_max]                                                          # Récupère la tournée du vaisseau le plus long
        if len(t) <= 3:                                                         # Si la tournée a moins de 2 planètes (hors dépôts), on ne peut pas faire de 2-opt
            return sol
        
        i, j = sorted(random.sample(range(1, len(t)-1), 2))                     # Choisit deux indices aléatoires i < j dans la tournée (on évite les dépôts)
        t[i:j+1] = t[i:j+1][::-1]                                               # Inverse le segment entre i et j
        return sol                                                              # Retourne la nouvelle solution voisine

    def voisin_relocate(solution: list[list], matrice_p) -> list[list]:
        """Relocate : prend une planète du vaisseau le plus chargé et la déplace vers un autre vaisseau choisi aléatoirement, à une position aléatoire.

        Avant :
            Vaisseau 1 (le plus long) : [1, 2, 3, 4, 5]
            Vaisseau 2                : [6, 7]
            Vaisseau 3                : [8, 9]

            On tire idx=2 → planète 3
            On la retire du vaisseau 1 → [1, 2, 4, 5]
            On choisit vaisseau 2 comme destination, pos=1

        Après :
            Vaisseau 1 : [1, 2, 4, 5]
            Vaisseau 2 : [6, 3, 7]      ← planète 3 insérée en pos 1
            Vaisseau 3 : [8, 9]
        """
        sol = copy.deepcopy(solution)
        k_max = max(range(K), key=lambda k: distance_tournee(sol[k], matrice_p))
        if len(sol[k_max]) <= 2:                                                # Si la tournée du vaisseau le plus long est vide, on ne peut pas relocaliser
            return sol
        
        idx = random.randrange(1, len(sol[k_max])-1)                            # Choisit une planète aléatoire dans la tournée la plus longue (on évite le dépôt)
        planete = sol[k_max].pop(idx)                                           # Retire la planète de la tournée du vaisseau le plus long

        autres = [k for k in range(K) if k != k_max]                            # Liste des autres vaisseaux, sans le vaisseau le plus long
        k_dest = random.choice(autres)                                          # Choisit un vaisseau de destination aléatoire parmi les autres
        pos = random.randint(1, len(sol[k_dest])-1)                             # Choisit une position aléatoire dans la tournée du vaisseau de destination
        sol[k_dest].insert(pos, planete)
        return sol

    def voisin_swap_inter(solution: list[list]) -> list[list]:
        """Swap inter-tournées : échange une planète entre deux vaisseaux différents.
        
        Avant :
            Vaisseau 1 : [1, 2, 3, 4]
            Vaisseau 2 : [5, 6, 7]

        On tire i1=1 (planète 2) et i2=2 (planète 7)
            → on les échange

        Après :
            Vaisseau 1 : [1, 7, 3, 4]
            Vaisseau 2 : [5, 6, 2]
        """
        sol = copy.deepcopy(solution)

        k1, k2 = random.sample(range(K), 2)                                     # On tire 2 vaisseaux différents au hasard (≠ relocate qui cible toujours le plus long)
        if len(sol[k1]) <= 2 or len(sol[k2]) <= 2:                             # Les deux tournées doivent avoir au moins 1 planète
            return sol
        
        i1 = random.randrange(1, len(sol[k1])-1)                                # On tire un indice aléatoire dans chaque tournée
        i2 = random.randrange(1, len(sol[k2])-1)

        sol[k1][i1], sol[k2][i2] = sol[k2][i2], sol[k1][i1]                     # On échange les planètes
        return sol

    VOISINAGES = [voisin_2opt, voisin_relocate, voisin_swap_inter]

    # ============================================================
    # --------------------------- VNS ----------------------------
    # ============================================================

    # Phase d'initialisation, si la solution initiale viole une contrainte de risque, on retente
    planetes = list(range(1, len(MATRICES_P)))
    sol_courante = solution_initiale(planetes, MATRICES_P, MATRICES_R)                     # Solution courante (initiale)
    tentatives = 0
    while not est_valide(sol_courante, MATRICES_P, MATRICES_R) and tentatives < 50:
        sol_courante = solution_initiale(planetes, MATRICES_P, MATRICES_R)
        tentatives += 1

    meilleure_sol = copy.deepcopy(sol_courante)                     # Meilleure solution globale
    meilleure_val = evaluer(sol_courante, MATRICES_P, MATRICES_R)                          # Valeur de la meilleure solution (distance max)
    historique = [meilleure_val]                                   # Historique de l'évolution de la meilleure valeur (pour analyse) 

    # Phase 2 — boucle principale (2000 itérations max)          

    for iteration in range(MAX_ITER):
        k_voisin = 0                                                # On repart toujours du voisinage 0 (2-opt)
        """
        À chaque itération on a une boucle interne qui parcourt les voisinages dans l'ordre :
            k_voisin=0 → 2-opt
            k_voisin=1 → relocate
            k_voisin=2 → swap inter
        """

        # Phase 3 — perturbation + recherche locale

        while k_voisin < MAX_VOISIN:                                # Tant que tous les voisinages n'ont pas été explorés

            if k_voisin == 2:  # swap n'a pas besoin de matrice_p
                voisine = VOISINAGES[k_voisin](sol_courante)
            else:
                voisine = VOISINAGES[k_voisin](sol_courante, MATRICES_P)

            for _ in range(10):                                     # Recherche locale légère : on tente 10 améliorations 2-opt sur ce voisin
                candidat = voisin_2opt(voisine, MATRICES_P)
                if evaluer(candidat, MATRICES_P, MATRICES_R) < evaluer(voisine, MATRICES_P, MATRICES_R):
                    voisine = candidat                              # On garde si c'est mieux (10 est un paramètre à ajuster)

            # Phase 4 - Décision

            val_voisine = evaluer(voisine, MATRICES_P, MATRICES_R)

            if val_voisine < evaluer(sol_courante, MATRICES_P, MATRICES_R):
                sol_courante = voisine                              # On accepte la solution voisine comme nouvelle solution courante
                k_voisin = 0                                        # On repart du voisinage 0 => on exploite à fond les améliorations 2-opt avant de passer aux autres.
                if val_voisine < meilleure_val:
                    meilleure_sol = copy.deepcopy(voisine)          # Nouvelle meilleure solution globale
                    meilleure_val = val_voisine
            else:
                k_voisin += 1                                       # Pas d'amélioration => on passe au voisinage suivant

        historique.append(meilleure_val)

    # Formatage de sortie standardisé
    is_feasible = est_valide(meilleure_sol, MATRICES_P, MATRICES_R)
    cycles_vaisseaux = {str(i + 1): route for i, route in enumerate(meilleure_sol)}

    return is_feasible, cycles_vaisseaux, meilleure_val, historique

## Agorithme génétique

Il s’inspire des mécanismes d’évolution biologique : sélection, croisement et mutation.

---

### Objectif du problème
On dispose :

- d’une matrice des distances MATRICES_P
- d’une matrice des risques MATRICES_R de K vaisseaux
- d’un seuil de risque MAX_LIFE (par vaisseau)
- L’objectif est de construire K cycles partant de la planète 0, visitant toutes les autres planètes, et revenant à 0, tout en :
- minimisant la distance maximale parmi les vaisseaux
- respectant la contrainte de risque pour chaque vaisseau

### Structure générale de l’algorithme
L’algorithme suit les étapes classiques d’un AG :

- Initialisation d’une population de solutions
- Évaluation via une fonction de fitness
- Sélection des parents
- Croisement pour créer de nouveaux individus
- Mutation pour introduire de la diversité
- Remplacement de la population
- Mise à jour du meilleur individu

Il répète ce cycle pendant un nombre donné de générations.

#### 1. Représentation d’un individu
Un individu est une liste de K routes 

#### 2. Création d’un individu initial
La fonction create_individual() :

- mélange aléatoirement les planètes
- les répartit équitablement entre les vaisseaux
- ajoute les retours à la base (0)

Cela garantit une population initiale variée.

#### 3. Fonction de fitness
La fitness combine :

- la distance maximale parmi les vaisseaux
- une pénalité si un vaisseau dépasse son seuil de risque

#### 4. Sélection (tournoi binaire)
Deux individus sont tirés au hasard, et le meilleur (fitness plus faible) est sélectionné comme parent.

#### 5. Croisement
Le croisement :

- récupère tous les nœuds visités par le parent 1
- les mélange
- les redistribue entre les vaisseaux

Ce mécanisme conserve la diversité tout en évitant les duplications.

#### 6. Mutation
La mutation déplace aléatoirement une planète d’un vaisseau vers un autre :

- elle ne s’applique qu’avec une probabilité p_mutate
- elle garantit que les solutions ne convergent pas trop vite

#### 7. Boucle principale
Pour chaque génération :

- on crée une nouvelle population via sélection + croisement + mutation
- on met à jour le meilleur individu global
- on enregistre la distance maximale dans historique

Cela permet d’observer la convergence de l’algorithme.

#### 8. Résultats retournés
La fonction renvoie :

- is_feasible : la solution respecte-t-elle les contraintes de risque ?
- cycles_vaisseaux : dictionnaire des routes finales
- max_dist : distance maximale réelle (sans pénalité)
- historique : évolution de la meilleure valeur au fil des générations

In [4]:
def genetic_algorithm(MATRICES_P, MATRICES_R, K=3, MAX_LIFE=15, pop_size=50, generations=500, p_mutate=0.2):
    """
    MATRICES_P : Matrice des distances (n x n)
    MATRICES_R : Matrice des risques/perte de vie (n x n)
    MAX_LIFE   : Seuil de risque (int ou liste de taille K)
    """
    n = MATRICES_P.shape[0]
    
    # Gestion du MAX_LIFE (si c'est un int, on le transforme en liste pour chaque vaisseau)
    if isinstance(MAX_LIFE, (int, float)):
        R_max = [MAX_LIFE] * K
    else:
        R_max = MAX_LIFE

    # --- Fonctions internes ---
    def create_individual():
        nodes = list(range(1, n))
        random.shuffle(nodes)
        routes = [[] for _ in range(K)]
        for i, node in enumerate(nodes):
            routes[i % K].append(node)
        return [[0] + r + [0] for r in routes]

    def route_distance(route):
        return sum(MATRICES_P[route[i], route[i+1]] for i in range(len(route)-1))

    def route_risk(route):
        return sum(MATRICES_R[route[i], route[i+1]] for i in range(len(route)-1))

    def fitness(ind):
        distances = [route_distance(r) for r in ind]
        risks = [route_risk(r) for r in ind]
        penalty = 0
        for k in range(K):
            if risks[k] > R_max[k]:
                # Pénalité proportionnelle au dépassement
                penalty += 10000 * (risks[k] - R_max[k] + 1)
        return max(distances) + penalty

    def selection(pop):
        # Tournoi binaire
        i, j = random.sample(range(len(pop)), 2)
        return pop[i] if fitness(pop[i]) < fitness(pop[j]) else pop[j]

    def crossover(p1, p2):
        # Logique de croisement : mélange des noeuds visités
        child_nodes = []
        for r in p1:
            child_nodes += r[1:-1]
        random.shuffle(child_nodes)
        
        routes = [[] for _ in range(K)]
        for i, node in enumerate(child_nodes):
            routes[i % K].append(node)
        return [[0] + r + [0] for r in routes]

    def mutate(ind):
        new_ind = copy.deepcopy(ind)
        if random.random() < p_mutate:
            k1, k2 = random.sample(range(K), 2)
            # On déplace un noeud du vaisseau k1 vers k2
            if len(new_ind[k1]) > 3: # 3 car [0, node, 0]
                i = random.randint(1, len(new_ind[k1]) - 2)
                node = new_ind[k1].pop(i)
                j = random.randint(1, len(new_ind[k2]) - 1)
                new_ind[k2].insert(j, node)
        return new_ind

    # --- Boucle principale de l'AG ---
    population = [create_individual() for _ in range(pop_size)]
    best_ind = min(population, key=fitness)
    historique = []

    for _ in range(generations):
        new_population = []
        for _ in range(pop_size):
            parent1 = selection(population)
            parent2 = selection(population)
            
            enfant = crossover(parent1, parent2)
            enfant = mutate(enfant)
            new_population.append(enfant)
        
        population = new_population
        current_best = min(population, key=fitness)
        
        if fitness(current_best) < fitness(best_ind):
            best_ind = current_best

        historique.append(max(route_distance(r) for r in best_ind))

    # --- Préparation du retour ---
    # Calcul des risques finaux pour vérifier la faisabilité
    final_risks = [route_risk(r) for r in best_ind]
    is_feasible = all(final_risks[k] <= R_max[k] for k in range(K))
    
    # Construction du dictionnaire des cycles
    cycles_vaisseaux = {str(i + 1): route for i, route in enumerate(best_ind)}
    
    # Distance max réelle (sans la pénalité)
    max_dist = max(route_distance(r) for r in best_ind)

    return is_feasible, cycles_vaisseaux, max_dist, historique

## Recherche Tabou

La recherche tabou est une méta‑heuristique d’optimisation qui améliore une solution en explorant son voisinage tout en évitant les retours en arrière grâce à une mémoire tabou.

---

### Objectif du problème
On cherche à construire K cycles :

- partant de la planète 0
- visitant toutes les autres planètes
- revenant à 0

tout en :

- minimisant la distance maximale parmi les vaisseaux
- respectant la contrainte de risque pour chaque route
- visitant chaque planète exactement une fois

### Structure générale de l’algorithme
La recherche tabou suit les étapes suivantes :

- Initialisation d’une solution de base
- Génération du voisinage
- Évaluation des solutions voisines
- Filtrage tabou (mémoire des mouvements interdits)
- Critère d’aspiration (autoriser un mouvement tabou si exceptionnel)
- Mise à jour de la solution courante et de la meilleure solution
- Répétition pendant un nombre d’itérations donné

#### 1. Représentation d’une solution
Une solution est une liste de K routes.

Chaque route commence et finit à 0.

#### 2. Initialisation
La solution initiale :

- répartit les planètes de manière cyclique entre les vaisseaux
- ajoute le retour à la base

Cela garantit une solution faisable (toutes les planètes sont visitées), même si elle n’est pas optimale.

#### 3. Fonction d’évaluation
La fonction evaluate() calcule :

- la distance maximale parmi les routes
- une pénalité si une route dépasse le seuil de risque.

#### 4. Génération du voisinage
La fonction get_neighbors() génère des solutions voisines en :

- retirant un nœud d’une route a
- l’insérant dans une autre route b à toutes les positions possibles

Chaque voisin est associé à un mouvement.

#### 5. Liste tabou et critère d’aspiration
La liste tabou empêche de refaire récemment un mouvement déjà exploré.
Un mouvement est tabou pendant tenure itérations.
Cependant, un mouvement tabou peut être accepté si :

il améliore la meilleure solution globale
→ critère d’aspiration

Cela permet d’éviter de bloquer une amélioration majeure.

#### 6. Boucle principale
À chaque itération :

- on parcourt tous les voisins
- on ignore les mouvements tabous (sauf aspiration)
- on sélectionne le meilleur voisin admissible

on met à jour :

- la solution courante
- la liste tabou
- la meilleure solution globale si faisable
- on enregistre la valeur dans historique

Cela permet d’observer la convergence.

#### 7. Résultats retournés
La fonction renvoie :

- is_feasible : la meilleure solution respecte-t-elle les contraintes ?
- cycles_vaisseaux : dictionnaire des routes finales
- max_distance : distance maximale réelle (sans pénalité)
- historique : évolution de la meilleure valeur au fil des itérations

In [18]:
def tabu_search(MATRICES_P, MATRICES_R, K=3, MAX_LIFE=15, iterations=300, tenure=7):
    """
    Exécute une recherche tabou pour le problème de tournées de véhicules.
    
    Retourne:
    - is_feasible (bool)
    - cycles_vaisseaux (dict)
    - max_distance (float)
    """
    N = len(MATRICES_P)
    START = 0

    # --- Outils internes ---
    def get_route_distance(route):
        return sum(MATRICES_P[route[i]][route[i + 1]] for i in range(len(route) - 1))

    def get_route_lives(route):
        return sum(MATRICES_R[route[i]][route[i + 1]] for i in range(len(route) - 1))

    def check_feasibility(routes):
        visited = []
        for r in routes:
            if get_route_lives(r) > MAX_LIFE:
                return False
            visited.extend(r[1:-1])
        return sorted(visited) == list(range(1, N))

    def evaluate(routes, penalty=1000):
        distances = [get_route_distance(r) for r in routes]
        max_dist = max(distances)
        violation = 0
        for r in routes:
            lives = get_route_lives(r)
            if lives > MAX_LIFE:
                violation += (lives - MAX_LIFE)
        return max_dist + penalty * violation

    def get_neighbors(routes):
        neigh = []
        for a in range(len(routes)):
            for b in range(len(routes)):
                if a == b: continue
                ra, rb = routes[a], routes[b]
                for i in range(1, len(ra) - 1):
                    node = ra[i]
                    new_ra = ra[:i] + ra[i+1:]
                    for j in range(1, len(rb)):
                        new_rb = rb[:j] + [node] + rb[j:]
                        new_sol = [list(r) for r in routes] # Copie rapide
                        new_sol[a] = new_ra
                        new_sol[b] = new_rb
                        neigh.append((new_sol, (node, a, b)))
        return neigh

    # --- Initialisation ---
    customers = list(range(1, N))
    current_sol = [[START] for _ in range(K)]
    for i, c in enumerate(customers):
        current_sol[i % K].append(c)
    for i in range(K):
        current_sol[i].append(START)

    best_sol = copy.deepcopy(current_sol)
    best_score = evaluate(best_sol)
    tabu_list = {} # move -> iteration d'expiration

    historique = []

    # --- Boucle principale ---
    for it in range(iterations):
        cand_best, cand_move, cand_score = None, None, math.inf

        for sol, move in get_neighbors(current_sol):
            score = evaluate(sol)
            
            # Critère d'aspiration : on ignore le tabou si on bat le record absolu
            is_tabu = move in tabu_list and tabu_list[move] > it
            if is_tabu and score >= best_score:
                continue

            if score < cand_score:
                cand_score, cand_best, cand_move = score, sol, move

        if cand_best is None:
            break

        current_sol = cand_best
        tabu_list[cand_move] = it + tenure

        # Mise à jour du meilleur score global si la solution est réalisable
        if cand_score < best_score and check_feasibility(current_sol):
            best_sol = copy.deepcopy(current_sol)
            best_score = cand_score

        if check_feasibility(current_sol):
            historique.append(best_score)
        else:
            historique.append(float('nan'))

    # --- Formatage de la sortie ---
    is_feasible = check_feasibility(best_sol)
    cycles_vaisseaux = {str(i + 1): route for i, route in enumerate(best_sol)}
    
    # On recalcule la distance max réelle sans pénalité
    max_distance = max(get_route_distance(r) for r in best_sol)

    return is_feasible, cycles_vaisseaux, max_distance, historique

## MILP :

#### (Milp Exact)

Cette méthode résout exactement le problème de tournées multi‑vaisseaux en formulant un **programme linéaire en nombres entiers (MILP)**.  
L’objectif rappelons le, est de **minimiser la distance maximale** parcourue par un vaisseau tout en respectant une contrainte de **risque maximal**.

---

##  Objectif du modèle

On cherche à construire `K` cycles :

- partant de la base `0`
- visitant chaque planète exactement une fois
- respectant un seuil de risque `MAX_LIFE`
- minimisant la **distance maximale** (variable `z`)

## Variables du modèle

- `x[v][i][j]` : 1 si le vaisseau `v` va de `i` vers `j`
- `y[v][i]` : 1 si le vaisseau `v` visite la planète `i`
- `u[v][i]` : variables MTZ pour éliminer les sous‑tours
- `z` : distance maximale à minimiser

## Contraintes principales

1. **Chaque planète est visitée une seule fois**  
   \(\sum_v y_{v,i} = 1\)

2. **Flux entrant = flux sortant** pour chaque planète visitée  
   garantit un vrai cycle

3. **Départ et retour à la base** pour chaque vaisseau utilisé

4. **Distance maximale**  
   \(\sum x_{v,i,j} \cdot d_{i,j} \le z\)

5. **Risque maximal**  
   \(\sum x_{v,i,j} \cdot r_{i,j} \le MAX\_LIFE\)

6. **Anti‑sous‑tours (MTZ)**  
   empêche la création de cycles internes non reliés à la base

##  Résolution et reconstruction

Le modèle est résolu avec CBC.  
Si la solution est optimale :

- les arcs `x[v][i][j] = 1` permettent de reconstruire chaque route
- on obtient les cycles de chaque vaisseau
- `z` donne la distance maximale réelle

## Résultats retournés

- **is_feasible** : solution optimale trouvée  
- **cycles_vaisseaux** : routes finales de chaque vaisseau  
- **max_distance** : distance maximale optimale  



In [6]:
def solve_milp_exact(MATRICES_P, MATRICES_R, K=3, MAX_LIFE=15):
    """
    Version corrigée du solveur exact MILP.
    """
    N = len(MATRICES_P)
    START = 0
    clients = [i for i in range(N) if i != START]
    
    model = pulp.LpProblem("MinMax_kTSP_Exact", pulp.LpMinimize)

    # --- Variables ---
    # On crée toutes les combinaisons i, j pour x
    x = pulp.LpVariable.dicts("x", (range(K), range(N), range(N)), cat="Binary")
    y = pulp.LpVariable.dicts("y", (range(K), range(N)), cat="Binary")
    u = pulp.LpVariable.dicts("u", (range(K), clients), lowBound=1, upBound=len(clients))
    z = pulp.LpVariable("z", lowBound=0)

    model += z

    # --- Contraintes ---
    for i in clients:
        model += pulp.lpSum(y[v][i] for v in range(K)) == 1

    for v in range(K):
        for i in clients:
            model += pulp.lpSum(x[v][j][i] for j in range(N) if j != i) == y[v][i]
            model += pulp.lpSum(x[v][i][j] for j in range(N) if j != i) == y[v][i]

    for v in range(K):
        # Départ et retour obligatoires si le véhicule est utilisé
        model += pulp.lpSum(x[v][START][j] for j in clients) <= 1
        model += pulp.lpSum(x[v][j][START] for j in clients) == pulp.lpSum(x[v][START][j] for j in clients)

    for v in range(K):
        model += pulp.lpSum(MATRICES_P[i][j] * x[v][i][j] for i in range(N) for j in range(N) if i != j) <= z

    for v in range(K):
        model += pulp.lpSum(MATRICES_R[i][j] * x[v][i][j] for i in range(N) for j in range(N) if i != j) <= MAX_LIFE

    # MTZ Anti-sous-tours
    M = len(clients)
    for v in range(K):
        for i in clients:
            for j in clients:
                if i != j:
                    model += u[v][i] - u[v][j] + M * x[v][i][j] <= M - 1

    # Résolution
    model.solve(pulp.PULP_CBC_CMD(msg=False))
    
    is_feasible = pulp.LpStatus[model.status] == 'Optimal'
    max_distance = pulp.value(z) if is_feasible and pulp.value(z) is not None else 0.0
    
    # --- Reconstruction des cycles (CORRIGÉE) ---
    cycles_vaisseaux = {}
    if is_feasible:
        for v in range(K):
            route = [START]
            curr = START
            # On limite la boucle pour éviter les tours infinis au cas où
            for _ in range(N):
                next_node = None
                for j in range(N):
                    if curr != j:
                        # pulp.value peut renvoyer None si la variable n'est pas utilisée
                        val = pulp.value(x[v][curr][j])
                        if val is not None and val > 0.5:
                            next_node = j
                            break
                
                if next_node is None or next_node == START:
                    break
                
                route.append(next_node)
                curr = next_node
            
            route.append(START)
            cycles_vaisseaux[str(v + 1)] = route
    else:
        cycles_vaisseaux = {str(v + 1): [0, 0] for v in range(K)}

    return is_feasible, cycles_vaisseaux, max_distance

## Relaxation Linéaire

Relaxation linéaire forte (Strong LP).

Cette méthode calcule une **borne inférieure** du problème en résolvant une **relaxation linéaire** du modèle exact.  
Elle remplace les variables binaires par des variables **continues entre 0 et 1**, ce qui rend le problème beaucoup plus facile à résoudre, mais les solutions obtenues ne correspondent plus à de vraies tournées.

---

## Objectif

Minimiser la **distance maximale** `z` parcourue par un vaisseau, sous contraintes :

- chaque planète est visitée exactement une fois (fractionnellement)
- les flux entrants et sortants sont cohérents
- chaque vaisseau peut partir et revenir au dépôt au plus une fois
- les contraintes de **distance** et de **risque** sont respectées (en version relaxée)

## Variables

- `x[v][i][j] ∈ [0,1]` : fraction d’arc utilisé par le vaisseau `v`
- `y[v][i] ∈ [0,1]` : fraction de visite de la planète `i` par `v`
- `z ≥ 0` : distance maximale à minimiser

Toutes les variables sont **continues**, ce qui supprime les contraintes combinatoires.

## Contraintes principales

1. **Visite fractionnaire unique**  
   \(\sum_v y_{v,i} = 1\)

2. **Flux fractionnaire cohérent**  
   entrée = sortie = \(y_{v,i}\)

3. **Départ/retour au dépôt limités**

4. **Distance maximale**  
   \(\sum x_{v,i,j} d_{i,j} \le z\)

5. **Risque maximal**  
   \(\sum x_{v,i,j} r_{i,j} \le MAX\_LIFE\)

## Résolution

Le modèle est résolu avec CBC.  
Comme les variables sont fractionnaires, **aucune vraie tournée n’est reconstruite** : seules les valeurs de `z` et la faisabilité sont pertinentes.

## Résultats retournés

- **is_feasible** : la relaxation a une solution optimale  
- **cycles_vaisseaux** : vides (pas de routes réelles en LP)  
- **max_dist** : valeur optimale de `z`, utilisée comme **borne inférieure**


In [7]:
def solve_strong_lp(MATRICES_P, MATRICES_R, K=3, MAX_LIFE=15):
    """
    Borne inférieure via relaxation linéaire.
    """
    N = len(MATRICES_P)
    model = pulp.LpProblem("Strong_LP", pulp.LpMinimize)

    # Variables continues entre 0 et 1 (Relaxation)
    x = pulp.LpVariable.dicts("x", (range(K), range(N), range(N)), 0, 1, cat="Continuous")
    y = pulp.LpVariable.dicts("y", (range(K), range(N)), 0, 1, cat="Continuous")
    z = pulp.LpVariable("z", lowBound=0)

    model += z

    # Chaque client visité au total une fois (somme des fractions = 1)
    for i in range(1, N):
        model += pulp.lpSum(y[v][i] for v in range(K)) == 1

    # Flux
    for v in range(K):
        for i in range(1, N):
            model += pulp.lpSum(x[v][i][j] for j in range(N) if j != i) == y[v][i]
            model += pulp.lpSum(x[v][j][i] for j in range(N) if j != i) == y[v][i]

    # Dépôt
    for v in range(K):
        model += pulp.lpSum(x[v][0][j] for j in range(1, N)) <= 1
        model += pulp.lpSum(x[v][j][0] for j in range(1, N)) <= 1

    # Distance max
    for v in range(K):
        model += pulp.lpSum(MATRICES_P[i][j] * x[v][i][j] for i in range(N) for j in range(N) if i != j) <= z

    # Vies
    for v in range(K):
        model += pulp.lpSum(MATRICES_R[i][j] * x[v][i][j] for i in range(N) for j in range(N) if i != j) <= MAX_LIFE

    model.solve(pulp.PULP_CBC_CMD(msg=False))

    is_feasible = pulp.LpStatus[model.status] == 'Optimal'
    
    # Pas de cycles réels en LP relaxation car les routes sont fractionnaires
    cycles_vaisseaux = {str(v + 1): [] for v in range(K)}
    max_dist = pulp.value(model.objective) if is_feasible else 0.0

    return is_feasible, cycles_vaisseaux, max_dist

# AFFICHAGE

In [8]:
NB_VEHICULE=3
MAX_LIFE=15



print("FAISABILITÉ, CYCLES, DISTANCES MAX\n")
for i in range(len(MATRICES_P)):
    print(f"--- Instance {i+1} - {len(MATRICES_P[i])} planètes ---")
    feasablility, cycles, res, _ = aco(MATRICES_P[i], MATRICES_R[i], K=NB_VEHICULE, MAX_LIFE=MAX_LIFE, alpha=1, beta=2, rho=0.4, Q=50, num_ants=40, num_iterations=200)
    print("ACO : ", feasablility, cycles, res)
    feasablility, cycles, res, _ = vns_search(MATRICES_P[i], MATRICES_R[i], K=NB_VEHICULE, MAX_LIFE=MAX_LIFE, MAX_ITER=2000, MAX_VOISIN=3)
    print("VNS : ", feasablility, cycles, res)
    feasablility, cycles, res, _ = genetic_algorithm(MATRICES_P[i], MATRICES_R[i], K=NB_VEHICULE, MAX_LIFE=MAX_LIFE, pop_size=50, generations=50, p_mutate=0.2)
    print("Génétique : ", feasablility, cycles, res)
    feasablility, cycles, res, _ = tabu_search(MATRICES_P[i], MATRICES_R[i], K=NB_VEHICULE, MAX_LIFE=MAX_LIFE, iterations=300, tenure=7)
    print("Taboue : ", feasablility, cycles, res)

    #print("MILP exact : ", solve_milp_exact(MATRICES_P[i], MATRICES_R[i], K=NB_VEHICULE, MAX_LIFE=MAX_LIFE)) #Attention il prend beaucoup de temps
    print("MILP relaxation : ", solve_strong_lp(MATRICES_P[i], MATRICES_R[i], K=NB_VEHICULE, MAX_LIFE=MAX_LIFE))
    print("\n")


FAISABILITÉ, CYCLES, DISTANCES MAX

--- Instance 1 - 10 planètes ---
ACO :  True {'1': [0, 5, 9, 3, 0], '2': [0, 1, 4, 8, 0], '3': [0, 6, 2, 7, 0]} 124
VNS :  True {'1': [0, 1, 4, 8, 0], '2': [0, 7, 2, 6, 0], '3': [0, 5, 9, 3, 0]} 124
Génétique :  True {'1': [0, 7, 4, 8, 0], '2': [0, 5, 1, 9, 0], '3': [0, 6, 3, 2, 0]} 126
Taboue :  True {'1': [0, 1, 4, 8, 0], '2': [0, 5, 9, 0], '3': [0, 7, 3, 2, 6, 0]} 124
MILP relaxation :  (True, {'1': [], '2': [], '3': []}, 50.666667)


--- Instance 2 - 20 planètes ---
ACO :  True {'1': [0, 8, 2, 12, 10, 9, 6, 0], '2': [0, 3, 13, 14, 4, 15, 5, 19, 0], '3': [0, 7, 16, 18, 17, 11, 1, 0]} 186
VNS :  False {'1': [0, 7, 16, 12, 10, 9, 5, 0], '2': [0, 15, 4, 19, 2, 8, 1, 6, 0], '3': [0, 3, 13, 14, 18, 17, 11, 0]} 190
Génétique :  True {'1': [0, 4, 14, 2, 19, 16, 7, 8, 0], '2': [0, 13, 12, 10, 5, 9, 6, 0], '3': [0, 3, 1, 17, 11, 18, 15, 0]} 298
Taboue :  True {'1': [0, 6, 1, 10, 12, 16, 7, 0], '2': [0, 8, 2, 14, 4, 19, 17, 18, 0], '3': [0, 3, 13, 5, 9, 15,